### ISSUE TITLE
PHP Warning: Undefined array key 1 in src/services.php on line 294

### ISSUE THREAD

**Issue by cliffordp** [stellarwp/slic#142]
Initial use of slic (previously I had used tric) and got this error when I ran this command:

`slic site-cli cli info`

Errors:

`PHP Warning:  Undefined array key 1 in ~/slic/src/services.php on line 294`

`Warning: Undefined array key 1 in ~/slic/src/services.php on line 294`

**Comment by cliffordp** [comment]
Possibly related but didn't see the issue happen at the previous command run - and running it again, got this error:

> PHP Warning:  rmdir(/Users/cliff/Documents/git/GitHub/slic/_wordpress/wp-content/plugins): Permission denied in ~/slic/src/utils.php on line 526
> Warning: rmdir(/Users/cliff/Documents/git/GitHub/slic/_wordpress/wp-content/plugins): Permission denied in ~/slic/src/utils.php on line 526

**Comment by cliffordp** [comment]
Another possibly related, even after recursively assigning _everyone_ read/write permission:

`PHP Warning: rmdir(~/slic/_wordpress): Directory not empty in ~/slic/src/utils.php on line 526`

`Warning: rmdir(~/slic/_wordpress): Directory not empty in ~/slic/src/utils.php on line 526`

**Comment by cliffordp** [comment]
Another possibly related error upon initializing `slic`:
`service "slic" is not running container #1`

**Comment by defunctl** [comment]
@cliffordp the main issue here is fixed in https://github.com/stellarwp/slic/releases/tag/1.2.4

If you're still experiencing the other issues here, please open up separate issues for each one.
