### ISSUE TITLE
Add Composer version to CLI info

### ISSUE THREAD

**Issue by cliffordp** [stellarwp/slic#143]
`slic site-cli cli info` should output the Composer version in use, just like it already does the PHP version

**Comment by defunctl** [comment]
This is controlled by [wp cli info](https://developer.wordpress.org/cli/commands/cli/info/) so if they don't display it, we unfortunately can't make them.

You can always run the following to verify:

```bash
slic composer --version
```

**Comment by cliffordp** [comment]
`slic composer --version` isn't working for me even though other slic commands are
<img width="516" alt="image" src="https://user-images.githubusercontent.com/1812179/220491973-fb75bb46-b0b5-4985-b3b1-968e30c21f6d.png">

**Comment by defunctl** [comment]
You need to have containers running, so if `docker ps` doesn't show any containers, you need run `slick up`

**Comment by cliffordp** [comment]
I thought I did but now when I ran `slic up` it pulled some images so maybe I was caught in the middle of some updating earlier...

✅ All containers are running.
`slic composer --version`
```
slic version 1.2.1 - StellarWP local testing and development tool
[composer:target] Composer version 2.5.4 2023-02-15 13:10:06
```

All good, amigo!
