### ISSUE TITLE
Containers leftover after an initial tric run prevent future runs from working

### ISSUE THREAD

**Issue by sc0ttkclark** [stellarwp/slic#63]
I just ran `tric run wpunit ....` and it completed the run successfully. However, I believe because it's passing the response through from the tric command now as of one of the recent releases -- it's not finishing the process to remove the rest of the containers properly.

Maybe it's unrelated, but I can see the containers still there and subsequent runs of the `tric run` all fail because of container problems.

![image](https://user-images.githubusercontent.com/709662/100679439-1eec0680-3335-11eb-9bac-92f812f00641.png)

**Comment by sc0ttkclark** [comment]
Error on re-run:

![image](https://user-images.githubusercontent.com/709662/100679533-4f33a500-3335-11eb-994d-b810ee1c931a.png)

**Comment by sc0ttkclark** [comment]
`tric down` resolves the problem for now as a workaround, but it would be great to fix this in an upcoming release.

**Comment by sc0ttkclark** [comment]
Still happening as of 0.5.16

![image](https://user-images.githubusercontent.com/709662/100896802-a2683d80-3484-11eb-996e-0ae73d7e50d3.png)

**Comment by borkweb** [comment]
This issue is resolved with the release of 1.0.0 - now keeping the containers running is the goal! 💃
