### ISSUE TITLE
Implement NVM

### ISSUE THREAD

**Issue by cliffordp** [stellarwp/slic#69]
We're to use tric to run Composer and NPM commands, for sake of consistency, but my plugin might need a different version of NPM than the v8.9 that comes with tric.

Adding NVM would allow us to `nvm use` my repo's `.nvmrc` file, also aimed at consistency.

FYI: I added a `tric-stack.yml` file to my repo, but it didn't take effect (assuming I did it correctly).

Also, I was surprised that running `tric npm --version` returns empty, as I expected `8.9`:
![image](https://user-images.githubusercontent.com/1812179/102640884-caac9900-4120-11eb-9c9c-cd8e467f0c97.png)

**Comment by borkweb** [comment]
This is done as of `slic` 1.0.0!
