### ISSUE TITLE
Wait for Chrome service to be up-and-working before starting tests

### ISSUE THREAD

**Issue by lucatume** [stellarwp/slic#73]
In [some instances](https://github.com/the-events-calendar/events-virtual/runs/1762010293#step:16:56) the `chrome` service that is being used in the acceptance test will not be ready to receive requests when the test starts.

The correct behavior would be for `tric` to check and wait to see if the `chrome` service is ready to accept requests or not.

**Comment by borkweb** [comment]
This was resolved with the 1.1.0 release.
